== Criterias

Every time we want to apply a transformation we want to target
specific nodes:

- A method with a specific `annotation`
- A class with a specific `annotation`
- A method with a specific `name`
- A method with a specific name `and` a specific annotation
- ...

Instead of holding a node reference and start calling methods from
that reference in order to find out which is the node we are
interested in, we can use criterias.

IMPORTANT: Criterias are available directly as static nodes in the
link:javadocs/asteroid/Criterias.html[`asteroid.Criterias`] or via
link:javadocs/asteroid/A.html[`A.CRITERIA`]

=== Transformers

Lets say we would like to apply a given transformation to a specific
set of classes annotated with a certain annotation.

[source, groovy]
.Criteria
----
include::{testMain}/asteroid/utils/AddImportTransformer.groovy[tags=classnodetransformer]
----
<1> Using a class node transformer
<2> Looking for a class node annotated with an annotation with name `AddImport`

What about looking for a `ClassNode` representing an inner class
having a specific name.

[source, groovy]
----
include::{testMain}/asteroid/global/samples/AddPropertyToInnerClass.groovy[]
----
<1> Again looking for a class node
<2> With a name containing a specific `Outer$Inner` class name

Now a different example. Instead of targeting a `ClassNode` we would
like to find a specific method call expression. We know what is the
name of the method we are calling, that's why we use
`methodCallByName` criteria here:

[source, groovy]
.ExpressionTransformer
----
include::{testMain}/asteroid/global/samples/ChangeTripleXToPlusOne.groovy[tags=expressiontransformer]
----

=== and / or

Sometimes using only one criteria could be limiting, sometimes we may
want to combine two or more criterias at once. For that purpose you can
use `A.CRITERIA.and` and `A.CRITERIA.or`. Check next example:

[source, groovy]
----
include::{testMain}/asteroid/global/samples/AddLoggerTransformer.groovy[tags=complexCriteria]
----
<1> Criteria looks for class nodes with name starting with
`asteroid.global.samples` and nodes containing `Logger` or nodes
ending with `Example`
<2> Applying the criteria in the constructor
<3> Adding a note to filtered nodes

=== As predicates

Although criteras were meant to be used in transformers, the way they
were designed makes them perfectly valid to be used as predicates when
filtering lists of AST nodes. The following example ask for all method
nodes from a given class node and then as any Groovy list tries to
find all methods that comply with the filter passed as parameter: `all
methods annotated with the **Important** annotation and with a name
starting with **get**`.

[source, groovy]
.Criterias in Local Transformations
----
include::{testMain}/asteroid/local/samples/criterias/CheckImportantMethodsImpl.groovy[tags=criteriasaspredicates]
----

Because criterias are just closures that eventually return a boolean
value they fit perfectly in this scenario.