language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: TZHfSMiEktDPAkL4hlonq9i1PxNeg0twVFiPlBTS/Hn++Rby3hmW3BwWLPugKLJ/pkVhAzvD5yoYzykVA3HHAPpj0xJLNZlTVOUzxD8uz5UQoHi0/QcV/gri3elRYYf9x37OIEViN8GLCeXxYV3OmkOzz0w2wLxPmF6PcoUab+M+48PK7cv3N6oU+GHfpNX8IvrLf9r4IolD1PNJD2J9KY+98Wx5j4cMqG1t2I1nKlgyIO83lnPxpNmBO6WWG5AyN+vPzTReMAT4w1VH6EJuNyfD3lkIpuaNcdZ0oP6jU4+ag/0LEToBnkWYcsLeBnMZeQnCEfsMXwlVPaR0Zbi2pXFeF6CB+mtm5r+xJXqkNrES58aP3COKT5/6zhBHyaAlZeBoB8S2SyGcwkHtBsJRuuRswUlrfpqueNqsbuSJk/j6ov8ooAC1O1t/U1OyeMrpwkLNiz1UCidIcGD0RMuTzjcdiyJmJl9wW+VEf0ZsCGCg6/8IUBEgJZJn2WfWIji7Sp1xH+MxzRrsBPKKUzMFdD/m2suCCOE3vNih+bSv/5KrBNkz9SU+bABhz5K9/3lM+IBG3TEGsH7qMXJonGMraXRhaBF1a8vzttQrlPKRY5DvfTe89Vvh8zZ9Ex0BnhoQXTRV2bPxSam9fFtzeqrmCpplIxOswqnju6H0I3J0guI=
  - secure: d8el0EK5PoLL1712koty5EMj4E93yec2c/zcIf/ZD4saufLWqYhoLc4QdAOf3F0CH/M6Tp1Bll/jkp8bl56VGILNpjulbn9O7ngbdWQCBEPNBwXiyZdBKIALVwKQUeBnjEsvS65lZ93NKDxo2ZjbS7suhev/bQQjn5MzhMp+YW3v5lNXFP8Bp4YVRiqo9rrUAEOC5GNn/zfy5D5Qm8SLIFTGfqTVscPZBDJkQf0g2F5I/xP31Q4kr5UHJ9zDPHbPbVYQdBiU/vx6KNKK8pQ7DX7H3sHDAcfWEsieXoUIz/tT9OGM+TKRVZPBSIblMD/tRWbmfh/TCukwRbp1rswG8mVAj4FVKIdmY0dr0p19uNkTWvGe7ilut7nUzl3FkzY1oFB82g2iwi1JfdsQYUTCiK1E7khxNZM6x7oHUEP0/t5MjwhEsVlUsqxhss6t5hUCOjljNssdFbuKg4QCiXqGK27hvPppHehWrZ8jjSh+uX7me2NUb33H8tV3GVoY86ovtMt8A47D0fC6rgu8H4df0RrB2er1VjD9Yr7VBk7LGgG4D5tnKpmbogChwA2Lxyk+GbUm+3jSNO2mnu2ewO6bNl9CPTgcGuqBoWBwP/i5XgcDtRQnMIWVWccl1rwu/DLlrlZqMi5xOdofjEW/dZgw23RttGTysqVUl+X220bGaBM=
install: "./gradlew assemble -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
script: "./gradlew clean build :asteroid-core:bintrayUpload -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
branches:
  only:
  - master
