language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: AK723QgKO9YC+OsNlW6KJECwdLuJz/stQj1/YZQjZh06cP3PGOMrv0JZWWq6F/MFqUqOXlKtP4D2eFkM70e87IdwP0D/94bXCSF6SFF4iRyjIjPARqJDeWwzUQ1MPRtccVlQsKIJzf/wtuDPCqjHyvYJImU+5Br02rFrXvRmYE09pFMOE6UuEkGiuHFMhXZBEJSIPCTOaOLKaC4ClNWhHxz68bqpMl+pb872jKGkbRZwfVtGF4ylZOEcYIpLbNgyMvRZg24eTh4EseONvFYNWbFCvyq5kz5s4kSWZpiA50ORpvCrYkQd3fMnzecataL/OURlxFHNaedv3SEc1/8maI4UXfN95qJmUAtx3WTEs6VilAD8abeAvLpv8cTn8mCwN/pa31/NxfUF6toKz4R/xmf05QAR9ey9HE47bCs5UHE6BX70Q4l6BEUMuKP+TgEogx2u5t6sO7kAtaDekME8luJqyJ0rEc/+EhJyhad/xoukNPONz3T2We8iuqOoYQeG+uDdvrQiwyG9rDV9gYkH9x3gsbGR0Zz/JaF0Xae6L0ksnSKJDJ/9RGz8o3zWwjtHvnAe0kL6tFlDU3Bh/3epfcm9C0+fxTgmzRW3OI6L5FzEaa+XKvZvPawnEoIgF44Psn1STo5yuMtCqGrJ/5wtpHyeOcQ/CejB4KmDFNMy6S4=
  - secure: GNYa9GKA5qtwbQEIxACmacUWV0oco6jRxDSRr9CVnH825rCD+1j7EhHFJl27Wkh1tSZ2RyHzO1x1cgdmWenN+yds1ldOseCUh6dRSqBeJ691GD2z3qjvuJfvtc5nYN7hqFMFUc6g2rMZBWZNy2SXhSu18uUMHYDpAK3r8AIQN8yfPQXtkf1aei2OYy9aLQ5LzetfML0PalNkopyYsonb5Oed71R+94e4HPFEXnR5bC/8gtOeZnL1NdkdvChed8OMsffXLIJlGfbPJ6kB30EGEA7mRbaq7eU9yahE9nbnoKMzdxxU8HUYxLQwXti0o59SOhPizzev7/Hz5ckWm0VSy373mq/TRzLjwEuObaUA4I3TkUs3CHy8h61h+WQwM/Fquwxk2ZNqH86pQm1SIg0HAWb1PFWuSnjFJZm6IEdCgHRpiweo5f3gWbpsaMWiwQVgQMpM9ShhHtSBzV154Goj1xSXR6kEgR3Ls0UG4rfoD3qB0rUomxx3S9Ao2bNRXA8hje19hmBcjERdQgZhh0w+bpIWGYYl2Ja/WRr5lJjvJuKTtAplxv7ZWWDywanjcD+2QQq321UHmZ0xxVrK9HtcjSeCn+2jx9EEjAyQ+Y9agKGhAqzZ7ZsWfkc7u48m0jvC3YHowNX2PUmdpiNZow7jWr1WMLyWcTWwszg9EJBrb8o=
install: "./gradlew assemble -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
script: "./gradlew clean build :asteroid-core:bintrayUpload -PbintrayUser=${bintrayUser}
  -PbintrayKey=${bintrayKey}"
branches:
  only:
  - master
