== Check

`Check` is an effort to avoid boiler plate code when checking the
AST state. Many times you have to check whether all precoditions are
correct before applying a given transformation. Without this sanity
check, many things could go wrong.

=== Local transformations

By default `Check` is available in Asteroid local transformations. All
you have to do is to structure your code using labels `check` and
`then`.

Here's an example, it's a bit silly but I think it will easy to
understand. We have a annotation called `@Serializable`.

The transformation `SerializableImpl` will make all classes annotated
with `@Serializable` to implement `java.io.Serializable`.

[source, groovy]
----
include::{testMain}/asteroid/local/samples/Serializable.groovy[]
----

As constraints I want to make sure:

- The annotated class package name should should start by 'asteroid'
- The annotated class can only have two method at most

[source, groovy]
----
include::{testMain}/asteroid/local/samples/SerializableImpl.groovy[]
----
<1> Checking the annotated class belongs to a certain `package`
<2> Checking that the annotated node has less than two methods
<3> Transformation code

To prove it, there's a test with an annotated class having two
methods:

[source, groovy]
----
include::{testTest}/asteroid/local/samples/SerializableTest.groovy[tags=checkersShouldFail]
----

And the test... passes :)

=== Your own transformations

If you would like to add this functionality in your project, you can
use Asteroid utility functions to inject this behavior in your code.

[source, java]
----
include::{coreMain}/asteroid/internal/LocalTransformationTransformation.java[tags=addCheckTo,indent=0]
----

This call is taken from Asteroid local transformations. Checking is added to method `doVisit`.