== Global Transformations

=== Introduction

"Global AST transformation are similar to local one with a major
difference: they do not need an annotation, meaning that they are
applied globally, that is to say on each class being compiled. It is
therefore very important to limit their use to last resort, because it
can have a significant impact on the compiler performance."
-- Groovy official site

`Asteroid` suggest a certain way of creating global AST
transformations. Instead of creating a global transformation and
manipulate the `SourceUnit` directly, an `Asteroid` global
transformation only holds references to code transformers.

[source, groovy]
----
include::{testMain}/asteroid/global/samples/AddTransformation.groovy[]
----
<1> Declaring class as a global AST transformation
<2> Extending `asteroid.global.GlobalTransformationImpl`
<3> Adding `asteroid.global.AbstractClassCodeExpressionTransformer` classes

A global transformation needs to be annotated with the
`@GlobalTransformation` annotation, then it should extend
`GlobalTransformationImpl` and finally to provide a list of the
transformers that will eventually transform the code.

In this example the code of the transformer is the following:

[source, groovy]
----
include::{testMain}/asteroid/global/samples/AddPropertyToInnerClass.groovy[]
----

<1> Because this transformer targets class nodes it extends `ClassNodeTransformer`
<2> Every `ClassNodeTransformer` requires a `SourceUnit` and a
criteria to filter class nodes
<3> Then the programmer should only be focused on develop de
transformation within the `transformClass` method

=== Node transformers

This type of transformers should be used when trying to transform a
given `ASTNode`. Think of a node as a method, a field, a class
everything that encloses code.

==== ClassNodeTransformer

#TODO

=== Expression transformers

#TODO

==== ExpressionTransformer

#TODO