== What is Asteroid

AST transformations, have been historically a hard topic in
Groovy. Asteroid is a set of utilities trying to reduce the complexity
of dealing with transformations.

If you have never done any AST transformation I'd recommend you to
take a look both the
http://groovy-lang.org/metaprogramming.html#developing-ast-xforms[Groovy]
documentation and the theory chapter. If you already now the stuff
then read on.

== Show me the code

=== Gradle

In order to use `Asteroid` in your Groovy code you can find it in Bintray:

[source,groovy]
----
repositories {
    maven {
        url  "http://dl.bintray.com/grooviter/maven"
    }
}
----

Then you can add the dependency to your project:

[source,groovy]
----
compile 'com.github.grooviter:asteroid:0.1.6'
----

=== Example

To show the benefit of using Asteroid, I will be following the
tutorial about local transformation available at the
http://www.groovy-lang.org/metaprogramming.html#transforms-local[Groovy
official site]. The code of the following example is available at the
`asteroid-test` module at
https://github.com/grooviter/asteroid/tree/master/asteroid-test[Github].

Given a code like the following:

[source, groovy]
----
include::{testTest}/asteroid/local/samples/WithLoggingTest.groovy[tags=testCode, indent=0]
----

We would like to print a start and stop message along with the message printed by the method itself. So in this
example we'll be expecting an output like:

[source, text]
----
start greet
Hello World
stop greet
----

For a local transformation only two things are required:

- The annotation used as a marker. In this example the `@WithLogging` annotation
- The transformation implementation

Lets see first the `@WithLogging` annotation declaration:

[source, groovy]
----
include::{testMain}/asteroid/local/samples/WithLogging.groovy[]
----
<1> This annotation will be applied to method elements.
<2> The `@Local` annotation only requires the class of the AST transformation implementation

NOTE: By default `@Local` annotation assumes the annotation is applied to a `type` (classes). If you would like to apply the
annotation to any other type of node, please use `@Apply` annotation and the correspondent element type.

Now it's time to implement the transformation. The transformation should be an instance of
`asteroid.LocalTransformationImpl`. We have to extend `LocalTransformationImpl` and provide two important generic
arguments:

- The annotation class used to mark our transformation: `WithLogging`
- The type of nodes that will be affected by this transformation. In this example `org.codehaus.groovy.ast.MethodNode`

[source,groovy]
----
include::{testMain}/asteroid/local/samples/WithLoggingTransformationImpl.groovy[]
----

<1> The `@LocalTransformation` annotation indicates that the following class is an implementation of a local
transformation. It also requires to specify the compilation phase this AST transformation will be applied. The
enumeration `A.PHASE_LOCAL` will show `ONLY` those compilation phases available for local transformations.
<2> Storing temporary the old code we want to transform which is an `org.codehaus.groovy.ast.stmt.Statement`
<3> Building `println "start"` code, which is wrapped in a `org.codehaus.groovy.ast.stmt.Statement`
<4> Building `println "end"` code, which is wrapped in a `org.codehaus.groovy.ast.stmt.Statement`
<5> Building the new method code re-arranging the new and old code in order. We are adding all previous in a
`BlockStatement` in the order we want them to execute.
<6> Building a generic `println constantValue` expression

The `@CompileStatic` annotation is not required it's only used here to highlight that all the code used in this
transformation is safely typed and can be optimized by this annotation.


== Overview

At the moment Asteroid is composed by two main groups, abstractions to
reduce the complexity of creating a new transformation, and utility
classes helping to create new Abstract Syntaxt Tree nodes.

[ditaa,align=center]
....

    +--------------------------------------+---------------------------------------------------+
    |                                      |                                                   |
    |         Transform Abstractions       |                 AST NODES FUNCTIONS               |
    |                                      |                    (asteroid.A)                   |
    |                                      |                                                   |
    +------------------+-------------------+-------------+------------+-----------+------------+
    |                  |                   |             |            |           |            |
    |      Local       |      Global       | EXPRESSIONS | STATEMENTS |   NODES   |   UTILS    |
    | (asteroid.local) | (asteroid.global) |   (A.EXPR)  |  (A.STMT)  | (A.NODES) |  (A.UTIL)  |
    |                  |                   |             |            |           |            |
    +------------------+-------------------+-------------+------------+-----------+------------+

....

=== Transform abstractions

So far abstractions used to deal with the AST were too low level. For
instance, you needed to check whether the nodes passed to your
transformation were the ones you wanted to act over or not, and then
proceed.

Asteroid tries to provide higher abstractions in order to reduce some
of the boiler plate code, and make the developer to focus on the
transformation only.

Both local and global abstractions are located in `asteroid.local` and
`asteroid.global` packages.

=== AST nodes functions

The other main part of Asteroid are functions dealing directly with
AST nodes. Functions responsible for modifying AST nodes.

They're divided in four groups:

* **Expressions**: Functions responsible for creating expressions
* **Statements**: Functions responsible for creating statements
* **Nodes**: Builders responsible for creating high level nodes
* **Utils**: Functions responsible for querying and querying any type of nodes

WARNING: With the upcoming `groovy-macro` module in Groovy 2.5.0 most
of the code in Asteroid, used for creating `expressions` and
`statements` may be gone for good in favor of the `macro` method.

==== The A class

All functions available in Asteroid are accessible through the
`asteroid.A` class.

Check javadoc: link:javadocs/asteroid/A.html[`asteroid.A`]
