== Local Transformations

=== Introduction

"Local AST transformations are relative to the context they are applied to. In most cases, the context is defined by an
annotation that will define the scope of the transform. For example, annotating a field would mean that the
transformation applies to the field, while annotating the class would mean that the transformation applies to the whole
class."
-- Groovy official site

To show the benefit of using Asteroid, I will be following the tutorial about local transformation available at the
http://www.groovy-lang.org/metaprogramming.html#transforms-local[Groovy official site].

Given a code like the following:

[source, groovy]
----
include::{testTest}/asteroid/local/samples/WithLoggingTest.groovy[tags=testCode, indent=0]
----

We would like to print a start and stop message along with the message printed by the method itself. So in this
example we'll be expecting an output like:

[source, text]
----
start greet
Hello World
stop greet
----

For a local transformation only two things are required:

- The annotation used as a marker. In this example the `@WithLogging` annotation
- The transformation implementation

Lets see first the `@WithLogging` annotation declaration:

[source, groovy]
----
include::{testMain}/asteroid/local/samples/WithLogging.groovy[]
----
<1> This annotation will be applied to method elements.
<2> The `@Local` annotation only requires the class of the AST transformation implementation

NOTE: By default `@Local` annotation assumes the annotation is applied to a `type` (classes). If you would like to apply the
annotation to any other type of node, please use `@Apply` annotation and the correspondent element type.

Now it's time to implement the transformation. The transformation should be an instance of
`asteroid.LocalTransformationImpl`. We have to extend `LocalTransformationImpl` and provide two important generic
arguments:

- The annotation class used to mark our transformation: `WithLogging`
- The type of nodes that will be affected by this transformation. In this example `org.codehaus.groovy.ast.MethodNode`

[source,groovy]
----
include::{testMain}/asteroid/local/samples/WithLoggingTransformationImpl.groovy[]
----

<1> The `@LocalTransformation` annotation indicates that the following class is an implementation of a local
transformation. It also requires to specify the compilation phase this AST transformation will be applied. The
enumeration `A.PHASE_LOCAL` will show `ONLY` those compilation phases available for local transformations.
<2> Storing temporary the old code we want to transform which is an `org.codehaus.groovy.ast.stmt.Statement`
<3> Building `println "start"` code, which is wrapped in a `org.codehaus.groovy.ast.stmt.Statement`
<4> Building `println "end"` code, which is wrapped in a `org.codehaus.groovy.ast.stmt.Statement`
<5> Building the new method code re-arranging the new and old code in order. We are adding all previous in a
`BlockStatement` in the order we want them to execute.
<6> Building a generic `println constantValue` expression

The `@CompileStatic` annotation is not required it's only used here to highlight that all the code used in this
transformation is safely typed and can be optimized by this annotation.

=== @Local

You can use `@Local` to use an annotation as an AST marker. The only
**mandatory** argument is the AST implementation class. Implementation
classes should always extend `asteroid.LocalTransformationImpl` class.

[source,groovy]
----
include::{testMain}/asteroid/local/samples/AsList.groovy[]
----

If `@Local` annotation is not used in combination with `@Apply` the
transformation is supposed to be used over an element of type `TYPE`,
meaning it will be applied over an entire class.

=== @Apply

`@Apply` is used in combination with `@Local` when the transformation
is applied to any element type other than `TYPE`: a method,
annotation, field...etc.

[source, groovy]
----
include::{testMain}/asteroid/local/samples/WithLogging.groovy[]
----

<1> This annotation will be applied to method elements.
<2> The `@Local` annotation only requires the class of the AST transformation implementation

=== @LocalTransformation

This annotation can only be used when coding a local transformation
implementation using Groovy. It saves some of the boilerplate code
needed to implement an instance of `asteroid.LocalTransformationImpl`.

[source, groovy]
----
include::{testMain}/asteroid/local/samples/AsListImpl.groovy[]
----

<1> This is a local transformation to be applied during `SEMANTIC_ANALYSIS` phase.

This transformation will be applied to those `ClassNode` instances
annotated with `@AsList`.

=== LocalTransformationImpl

`asteroid.LocalTransformationImpl` exists to avoid some of the
defensive code that you would normally write at the beggining of an
AST transformation.

When coding an AST transformation you always check that the first node
is an `AnnotationNode` and the second is the type of `ASTNode` you
expected to be annotated by the first node. Instead of coding that you
can use `LocalTransformationImpl`.

Lets say I have an annotation `@ToMD5`. That annotation can only be
used in elements of type `FIELD`:

[source, groovy]
----
include::{testMain}/asteroid/local/samples/ToMD5.groovy[]
----

I would like to create a method for every field annotated by `ToMD5`
returning the MD5 signature of the content of that field.

In order to implement that I'm using `LocalTransformationImpl`:

[source, groovy]
----
include::{testMain}/asteroid/local/samples/ToMD5Impl.groovy[]
----

<1> Declaring this class as the implementation of a local AST
transformation using `LocalTransformation`
<2> Creating a class extending `LocalTransformationImpl` and declaring
that the annotation and the affected node type are `ToMD5` and
`FieldNode` respectively
<3> The override method declares the correct generic type `FieldNode`.

From this line on you don't have to be worried about casting first and
second node passed to your transformation anymore.
